name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Panquesito7/setup-jule@v1.1.1
        with:
          version: dev
          directory: .
          add-to-path: true
          extra-command: version 

      - name: Compile Tests
        run: |
          julec -t .
          clang++ -O0 --std=c++17 -Wno-everything -o ./tests.out ./dist/ir.cpp
          git update-index --add --chmod=-x ./tests.out
          chmod +x ./tests.out

      - name: Run Tests
        run: |
          ./tests.out

      - name: Cleanup
        run: |
          rm -f tests.out
